# Generated by Django 5.0.2 on 2025-08-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=100)),
                ('players_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.sport'),
        ),
    ]
