# Generated by Django 5.0.2 on 2025-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0002_team_remove_player_team_name_player_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=100)),
                ('Sport', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball')], max_length=50)),
                ('Coach_Name', models.CharField(max_length=100)),
                ('Number_of_Players', models.PositiveIntegerField()),
            ],
        ),
    ]
