# Generated by Django 5.0.2 on 2025-08-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0003_newteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
