# Generated by Django 5.0.2 on 2025-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0004_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_1_Name', models.CharField(max_length=50)),
                ('Team_2_Name', models.CharField(max_length=50)),
                ('Match_Date', models.DateField()),
                ('Match_Time', models.TimeField()),
                ('Location', models.CharField(max_length=100)),
                ('Final_Score', models.CharField(blank=True, max_length=20, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
