# Generated by Django 5.0.2 on 2025-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0005_basketballgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Game', models.CharField(max_length=100)),
                ('Indoor_Outdoor', models.CharField(max_length=100)),
            ],
        ),
    ]
