# Generated by Django 5.0.2 on 2025-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_newgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
